M48
; DRILL file {KiCad 9.0.1} date 2025-06-08T22:19:18+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-08T22:19:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X113.6Y-72.9
X113.6Y-77.9
T2
X70.17Y-66.5
X70.17Y-69.5
T3
X71.0Y-59.5
X71.0Y-94.5
X116.0Y-59.5
X116.0Y-94.5
M30
